{
  "home": [
    {
      "id": 1,
      "name": "Шестеренка",
      "text": "В данном уроке Вы сможете ознакомиться с основными командами Fusion 360 и построить простейшую деталь используя только один компонент."
    },
    {
      "id": 2,
      "name": "Коллектор",
      "text": "В данном уроке Вы сможете закрепить материал который уже прошли, узнать новые функции и построить деталь из одного компонента."
    },
    {
      "id": 3,
      "name": "Отвёртка",
      "text": "В данном уроке, используя команды, которые были в предыдущих уроках, Вы научитесь сопрягать компоненты и соберете свою первую сборку."
    },
    {
      "id": 4,
      "name": "Клещи",
      "text": "В данном уроке Вы научитесь работать с большим количеством компонентов и правильно их сопрягать."
    },
    {
      "id": 5,
      "name": "Мальтийский крест",
      "text": "В данном уроке Вы соберете сборку из пяти компонентов и сможете ознакомиться с более обширным функционалом Fusion 360."
    },
    {
      "id": 6,
      "name": "Лампочка",
      "text": "В данном уроке Вы закрепите все свои знания из прошедших уроков и соберете лампочку."
    },
    {
      "id": 7,
      "name": "Тески",
      "text": "В данном уроке Вы закрепите все свои знания из прошедших уроков и соберёте ешё одну сборку."
    },
    {
      "id": 8,
      "name": "Руки-ножницы",
      "text": "В данном уроке, Вы научитесь работать с большим количеством компонентов и правильно их сопрягать."
    },
    {
      "id": 9,
      "name": "",
      "text": ""
    }
  ],
  "guides": [
    {
      "id": 1,
      "parts": [
        {
          "name": "Гайд",
          "content": "Откройте Autodesk Fusion 360. Нажимите на верхней вкладке слева Sketch (набросок) -> Create Sketch (создание наброска) и выберите ось ZX.^1.jpg^После добавления нового наброска, выбираем Sketch (набросок) -> Circle(окружность) -> Center Diameter Circle (создание окружности по диаметру). Из центра осей зажимая левую кнопку мыши растягиваем круг нужной длины. По умолчанию стоят мм. При растяжении будет появляться окошко, в котором вы можете вписать размер окружности (47мм).^2.jpg^Нам потребуется еще одна окружность, но уже малого размера(8мм). Также выбираем Sketch (набросок) -> Circle(окружность) -> Center Diameter Circle (создание окружности по диаметру).^3.jpg^Также, создаем еще одну окружность размером в 10мм.^4.jpg^Мы сделали наш набросок и можем приступать к созданию детали. Для этого зажимая Shift, мы выбираем те поверхности, которые хотим выдавить (сделать объемными). После выбора, нажимаем на верхней вкладке Create -> Extrude (выдавить). Выбираем поверхность самого большого круга. У нас появляется стрелочка и окошко справа (параметры). Благодаря параметрам мы можем настраивать выдавливание как нам требуется (в одну сторону или в обе, дистанция и т.п.). Выдавливаем нашу большую окружность на 10мм.^5.jpg^Окружность поменьше, выдавливаем в ту же сторону на 11мм.^6.jpg^У нас выдавилась основа шестерёнки. Далее выбираем верхнюю поверхность правой копкой мыши и нажимаем Sketch -> Create Sketch (создание нового наброска).^7.jpg^У нас открылся новый эскиз.^8.jpg^По верхней оси создаем линию вниз, Sketch -> Line (Линия). Задаем длину 2мм. Для того, чтобы закончить линию, вы можете нажать Escape.^9.jpg^Создаём из этой же точки линию вверх, 0.50мм.^10.jpg^Из нижнего конца первой линии в право создаем еще одну линию 0.50мм^11.jpg^Из этой же точки, создаем в лево линию 0.50мм.^12.jpg^Из верхнего конца второй созданной линии в право создаем линию длинной 1.25мм.^13.jpg^Из этой же точки создаем в лево линию 1.25мм.^14.jpg^Соединяем концы проведенных в стороны линий. У нас получилась трапеция. Выбираем с помощью Shift-а всю поверхность этой трапеции (как мы делали в шаге №6).^15.jpg^После того, как мы выбрали всю трапецию, можем переходить к созданию зубчика. Для этого, нам потребуется действие Extrude (как в шаге №6). Мы должны убедиться в том, что выдавливание произойдет в нужную сторону (через всю деталь), для этого, посмотрите и убедитесь, что стрелочка направлена туда, куда нужно. Также, мы можем выбрать на какое расстояние выдавится наша деталь. Для этого в параметрах в окошке справа нажимаем Start -> Object и выбираем противоположную сторону детали.^16.jpg^Для того, чтобы получились полноценные зубчики на всей поверхности детали, прибегнем к помощи массива. Для этого на вкладке Create выбираем Pattern -> Circular Pattern.^17.jpg^Выбираем три внутренние стороны зубчика левой кнопкой мыши^18.jpg^В окошке параметров переключаемся на Axis (ось) и выбираем нашу большую окружность^19.jpg^После чего, нам надо увеличить число зубчиков. В этом нам поможет Quantity (окошко параметров). Задаем число 45 и нажимаем ОК.^20.jpg^Вот что у нас получилось.^21.jpg^Теперь, нам надо сгладить окружность, которая выпирает. Выбираем всю деталь нажимаем Modify -> Fillet. Выбираем окружность соединения большой окружности и малой. Вводим параметры 1 мм и нажимаем ОК.^22.jpg^Наша деталь готова. Осталось все сохранить. Для этого в самой верхней вкладке нажимаем File -> Save и сохраняем нашу деталь.^23.jpg^"
        },
        {
          "name": "Видео",
          "content": "https://www.youtube.com/embed/CQXrY3CFG1s"
        }
      ]
    },
    {
      "id": 2,
      "parts": [
        {
          "name": "Гайд",
          "content": "Перед тем как начать, вам необходимо запустить Fusion 360. Далее, Вам необходимо нажать на кнопку \"Show Data\", которая находится в правом левом углу.^1.jpg^У нас открылось окно и появилась кнопка \"New Project\". Создаем новый проект и выбераем его как активный, нажав по нему два раза \"ЛКМ\".^2.jpg^Нажимаем «SKETCH» и выбираем инструмент «Center Diameter Circle», который позволит нам создать круг по указанному диаметру.^3.jpg^Создаём на любой плоскости два круга с диаметрами, указанными в чертеже (60 и 40) из одной точки с координатами 0.^4.jpg^Создаём на расстоянии 100 от центра отрезок произвольной длины.^5.jpg^Нажимаем \"Stop Sketch\", тем самым завершая работу над чертежом.^6.jpg^Вернувшись в основное меню, выбираем «CREATE» - «Revolve». Выбираем внешний круг, который будет стенками нашей трубы. Осевая линия выбирается автоматически. В ином случае – указать на начерченный ранее отрезок. В настройках поставить 70 градусов. «Щелкаем Ок».^7.jpg.^8.jpg^Выбираем инструмент «Extrude», нажимаем на плоскость «стенок» трубы и задаём расстояние 25. Повторяем это для другого конца трубы.^9.jpg^Снова выбираем скетч, на этот раз нажимаем на плоскость трубы, которую мы ранее выдавливали.^10.jpg^Создаём эскиз. Скругления добавим после. Пользуемся инструментами «Rectangle» и «Circle». Для того, чтобы создать указанные отверстия – нарисуем квадрат с указанными (64) сторонами. На его углах добавляем по окружности с радиусом 8.^11.jpg.^12.jpg^Заканчиваем эскиз и выбираем инструмент «Extrude». Выбираем на чертеже только то, что нам нужно. В размер пишем «-10», благодаря чему выдавливание будет произведено в другую сторону.^13.jpg^Наша деталь готова.^14.jpg"
        },
        {
          "name": "Видео",
          "content": "https://www.youtube.com/embed/5Jh0En39dNM"
        }
      ]
    },
    {
      "id": 3,
      "parts": [
        {
          "name": "Ручка",
          "content": "Создадим первую деталь - ручку. Начинаем наш эскиз с выбора рабочей плоскости. В правой верхней части находим «кубик» и выбираем Front, как показано на рис.1.^image001.jpg^^image001.jpgНаносим первоначальные очертания чертежа, указывая необходимые размеры с помощью инструмента Sketch Dimension. (Рис. 2)^image002.jpg^В разделе Create выбираем инструмент Revolve. Для того чтобы применить “вращение” к получившемуся эскизу, нужно выбрать профиль и в разделе Axis выбрать вспомогательную линию на оси X, которая лежит в основании эскиза. (Рис. 3)^image003.jpg^Создаем эскиз на виде спереди, строим окружность, выставляя необходимые размеры. (Рис. 4)^image004.jpg^Затем проводим вспомогательную линию в центре фигуры и инструментом Revolve создаем вращение. (Рис. 5)^image005.jpg^Делаем этот эскиз видимым, нажимая на лампочку. (Рис. 6)^image006.jpg^nВ разделе Create нажимаем Pattern->Pattern on Path. В панели Objects выбираем наше вращение, а в панели Path указываем вспомогательную линию. Значения ставим как на рис. 7. Лампочку выключаем.^image007.jpg^На виде слева делаем новый эскиз, строим окружность выполняя необходимые размеры. (Рис. 8)^image008.jpg^Выполняем выдавливание инструментом Extrude на всю длину. (Рис. 9)^image009.jpg^В разделе Create нажимаем Pattern->Circular Pattern. В панели Objects выбираем наше выдавливание, а в панели Axis нажимаем на основание детали. Значения ставим как на рис. 10.^image010.jpg^На английской раскладке нажимаем на букву A и выбираем материал ручки отвертки. (Рис. 11)^image011.jpg^^image012.jpg^Создаем новый эскиз, строим окружность. (Рис. 13)^image013.jpg^Выдавливаем его на 30 мм внутрь и сохраняем деталь. (Рис. 14)^image014.jpg^"       },
        {
          "name": "Стержень",
          "content": "Создадим вторую деталь - стержень. Начинаем наш эскиз с выбора рабочей плоскости. В правой верхней части находим «кубик» и выбираем Front, как показано на рис. 15.^image015.jpg^Строим прямоугольник с размерами 100 мм на 1.5 мм. (Рис. 16)^image016.jpg^Затем наносим эскиз, который показан на рис.17 ^image017.jpg^Выполняем вращение. (Рис. 18)^image018.jpg^На виде сверху создаем эскиз, строим прямоугольник и вспомогательную линию, указываем размеры. (Рис. 19)^image019.jpg^Выдавливаем прямоугольник на 0.75 мм как показано на рис. 20^image020.jpg^В разделе Create нажимаем Pattern->Circular Pattern. В панели Objects выбираем наше выдавливание, а в панели Axis нажимаем на основание детали. Значения ставим как на рис. 21^image021.jpg^Делаем фаску радиусом 1 мм с помощью инструмента Chamfer. (Рис. 22)^image022.jpg^Нажимаем на Construct, а затем на головку отвертки и перемещаем плоскость на 3 мм. (Рис. 23)^image023.jpg^Создаем эскиз на этой плоскости и строим прямоугольник по размерам. (Рис. 24)^image024.jpg^Затем снова нажимаем на Construct, выбираем первую плоскость и перемещаем вторую плоскость на 7 мм от первой. (Рис. 25)^image025.jpg^Создаем эскиз на второй плоскости и строим прямоугольник по размерам. (Рис. 26)^image026.jpg^В разделе Create выбираем инструмент Loft. Поочередно нажимаем на головку отвертки и на эскизы. В профиле 1 жмём на Tangent (G1), а в профиле 3 на Direction. (Рис. 27)^image027.jpg^Выбираем материал для стержня и сохраняем деталь. (Рис. 28)^image028.jpg^"
        },
        {
          "name": "Сборка",
          "content": "Соберём наши детали. Создаем новый проект и сохраняем его. (Рис. 29)^image029.jpg^Перетаскиваем стержень отвертки и ручку в сборку. (Рис. 30)^image030.jpg^В разделе Assemble выбираем Joint и совмещаем стержень с ручкой местами, которые показаны на рис. 31^image031.jpg^ Наша отвёртка готова! (Рис. 32)^image032.jpg^Не забудьте сохранить сборку!"
        }
      ]
    },
    {
      "id": 4,
      "parts": [
        {
          "name": "Корпус",
          "content": "Перед тем как приступить к постройке корпуса, вам необходимо запустить Fusion 360. Создадим эскиз. Для этого в левом меню выбираем плоскость XY, щелкаем левой кнопкой мыши и наживаем “Create Sketch”.^1.jpg^Нам понадобится создать прямоугольник. Для этого в меню “Sketch” выбираем “2-Point Rectangle”.^2.jpg^Кликаем в случайное место плоскости, отводим немножко мышку в сторону. Получается прямоугольник. Задаем размеры “44” в длину и “7” в ширину. Для переключения между размерами нажмите Tab. В итоге должно получиться как на рис. ниже (если он будет стоять вертикально, то не страшно). Нажимаем Enter.^3.jpg^Далее необходимо скруглить края. Для этого в меню “Sketch” выбираем “Fillet”.^4.jpg^Нажимаем на 2 любые смежные грани (либо на угол между ними). Угол закруглится. В поле размера введем “3.5”. Повторим для всех граней.^5^6.jpg^Далее нам необходимо создать отверстия. Для этого в меню “Sketch” выбираем “Center Diameter Circle”.^7.jpg^Далее нажимаем на точку, на которую показывает стрелочка.^8.jpg^Отводим мышку немного в сторону и в поле размера вводим “4”. Нажимаем Enter. Повторяем также, с другой стороны.^9.jpg^В меню “Create” выбираем функцию “Extrude”.^10.jpg^Нажимаем на наш эскиз, чтобы он выделился синим. Не выделяйте окружности, если выделили, то нажмите по ним ещё раз. В поле размера введите “5”. Нажмите Enter.^11.jpg^Далее необходимо покрасить деталь. Для этого необходимо на вкладке “Modify” нажать на “Appearance”. В появившемся справа окне идите по пути “Plastic –> Translucent”. Среди цветов в папке “Translucent” выберите желтый и мышкой потяните его на деталь. В итоге мы получили такую деталь.^12.jpg^Нам понадобится ещё одна деталь. Для начала создаем эскиз. Для этого в левом меню выбираем плоскость XY, щелкаем левой кнопкой мыши и наживаем “Create Sketch”. Создадим прямоугольник. Для этого в меню “Sketch” выбираем “2-Point Rectangle”.^13.jpg^Кликаем в случайное место плоскости, отводим немножко мышку в сторону. Получается прямоугольник. Задаем размеры “35.2” в длину и “6.4” в ширину. Для переключения между размерами нажмите Tab. В итоге должно получиться как на рис. ниже. Нажимаем Enter.^14.jpg^Далее необходимо скруглить края. Для этого в меню “Sketch” выбираем “Fillet”.^15.jpg^Нажимаем на 2 любые смежные грани (либо на угол между ними). Угол закруглится. В поле размера введем “3.5”. Повторим для всех граней.^16^17.jpg^Далее нам необходимо создать отверстия. Для этого в меню “Sketch” выбираем “Center Diameter Circle”.^18.jpg^Далее нажимаем на точку, на которую показывает стрелочка.^19.jpg^Отводим мышку немного в сторону и в поле размера вводим “4”. Нажимаем Enter.^20.jpg^Повторяем также, с другой стороны.^21.jpg^В меню “Create” выбираем функцию “Extrude”.^22.jpg^Нажимаем на наш эскиз, чтобы он выделился синим. Не выделяйте окружности, если выделили, то нажмите по ним ещё раз. В поле размера введите “10.5”. Нажмите Enter.^23.jpg^Кликаем на верхнюю поверхность левой кнопкой мыши и в меню выбираем “Create Sketch”.^24.jpg^Создаем окружность на поверхности с диаметром 7 мм.^25.jpg^Для выравнивания круга нам понадобится функция “Sketch Dimension” во вкладке “Sketch”. Таким образом мы сможем указать на каком расстоянии находится круг от граней.^26.jpg^После, нажимаем на центр окружности и на грань, на которую указывает стрелка, и отводим мышь на пространство между окружностью и гранью.^27.jpg^Кликаем мышью и в поле размера вводим “14”. Если допустили ошибку при вводе размера, вы можете удалить его и поставить снова, либо просто дважды кликнуть на уже получившийся, чтобы снова вызвать поле ввода размера.^28.jpg^Аналогично задаем расстояние между центром окружности и верхней гранью. В поле вводим “5.25”.^29.jpg^Получившуюся окружность выдавливаем на расстояние «60.5».^30.jpg^Для сборки, нам потребуется корпус. Создаем эскиз. Для этого в левой части экрана выбираем плоскость XZ, нажимаем левой кнопкой мыши и в появившемся меню выбираем “Create Sketch”.^31.jpg^Для создания первого эскиза мы воспользуемся инструментом \"Center rectangle\", который находится в выпадающей вкладке \"Sketch\"->\"Rectangle\"->\"Center rectangle\".^32.jpg^Далее наводим мышку на центральную точку плоскости, на которой находится эскиз.^33.jpg^Нажимаем левой кнопкой мыши и растягиваем наш прямоугольник. Для того чтобы задать ему размер, мы вводим значения ширины и длины, переключаясь между ними через клавишу \"Tab\" на клавиатуре.^34.jpg^Для ширины вводим размер 25.5 мм, а для длины 65 мм. Нажимаем \"Enter\". Если нужно исправить размер, дважды кликаем на него и вводим нужное значение. Если необходимо задать размер, то пользуемся инструментом \"Sketch dimension\", который находится в выпадающей вкладке \"Sketch\"->\"Sketch dimension\".^35.jpg^Размеры задаются нажатием на прямую, чью длину мы хотим задать, либо нажатием между двумя прямыми и вводом значения расстояния между ними. Нажимаем клавишу \"Stop sketch\" в верхней части экрана, чтобы закрыть эскиз.^36.jpg^Затем выбираем \"Extrude\" в верхней части экрана, чтобы выдавить наш эскиз.^37.jpg^Нажимаем на наш эскиз, вводим значение 7 мм (в поле Distance), на которое будем выдавливать и нажимаем \"ОК\".^38.jpg^Далее выбираем верхнюю грань, нажимаем правую кнопку мыши и создаём второй эскиз, который будет располагаться уже на верхней грани.^39.jpg^Задаём размеры для прямоугольника 10.5 мм и 6.4 мм^40.jpg^А также задаём размеры от центральной точки эскиза 5.25 мм и 32.5 мм^41.jpg^Затем выбираем инструмент \"Line\" во вкладке \"Sketch\".^42.jpg^Проводим осевую линию размером 10 мм из центральной точки эскиза.^43.jpg^С помощью этой линии мы будем использовать инструмент «зеркалирование» на прямоугольник, для этого выбираем \"Mirror\" во вкладке \"Sketch\".^44.jpg^Выбираем линии прямоугольника, который будем копировать.^45.jpg^Затем нажимаем кнопку \"Select\" напротив \"Mirror Line\", нажимаем на нашу осевую линию и нажимаем \"ОК\".^46.jpg^Потом завершаем эскиз и выдавливаем оба прямоугольника на расстояние 26.2 мм. Если программа, по неизвестной причине, показывает, что выдавливание будет происходить в другую сторону (не так как на скриншоте), то в поле расстояния введите -26.2 мм.^47.jpg^Создаем третий эскиз на грани одного из выдавленных прямоугольников.^48.jpg^Создаём прямоугольник с размерами 10.5 мм и 65 мм из центральной точки эскиза.^49.jpg^Потом завершаем эскиз и выдавливаем его на расстояние 6.4 мм. Если выдавливание происходит не так как на скриншоте, то в поле расстояния напишите -6.4 мм.^50.jpg^Наверху выдавленного параллелепипеда создаём ещё один эскиз.^51.jpg^Используем окружность, для этого находим во вкладке \"Sketch\" инструмент \"Circle\" и выбираем \"Center Diameter Circle\".^52.jpg^Из центральной точки отводим мышку и задаём диаметр 7 мм.^53.jpg^Потом завершаем эскиз и выдавливаем окружность на 29 мм.^54.jpg^Сверху цилиндра создаём эскиз.^55.jpg^Из центральной точки задаём прямоугольник с размерами 46 мм и 20.5 мм.^56.jpg^Потом завершаем эскиз и выдавливаем прямоугольник на 7 мм.^57.jpg^Делаем на нём ещё один эскиз.^58.jpg^Создаем прямоугольник с размерами 6.4 мм и 10.5 мм.^59.jpg^Для него задаём дополнительные размеры 5.25 мм и 23 мм для выравнивания на эскизе.^60.jpg^Создаём осевую линию и используем \"Mirror\", как это делали в прошлый раз^61.jpg^Потом завершаем эскиз и выдавливаем на расстояние -7 мм. Значение задаётся со знаком \"минус\", чтобы сделать вырез, а не выдавливание. В поле Operation должна быть операция Cut.^62.jpg^Следующим этапом будет создание седьмого эскиза, который будет располагаться на боковой части последнего выдавливания на длинной стороне.^63.jpg^Задаём две окружности диаметром 4 мм.^64.jpg^Задаём дополнительные размеры 72.1 мм и 19.5 мм для выравнивания окружностей на эскизе.^65.jpg^Потом завершаем эскиз и выдавливаем их со значением -100 мм (операция Cut).^66.jpg^Далее нашей фигуре делаем некоторые грани скруглёнными, для этого в выпадающей вкладке \"Modify\" выберем инструмент \"Fillet\".^67.jpg^После чего выбираем грани.^68.jpg^Задаем значение 3.5 мм в поле ввода радиуса.^69.jpg^Добавим пару отверстий в основание фигуры, выбираем плоскость снизу и создаём очередной эскиз.^70.jpg^Задаём две окружности: большая диаметром 7 мм задаётся из центральной точки эскиза, а малая диаметром 4 мм на расстоянии 15 мм от большой.^71.jpg^В окне справа, в котором расположены инструменты зависимостей выберем инструмент \"Horizontal / Vertical\".^72.jpg^Далее левой кнопкой мыши кликаем по центрам окружностей, и они выравниваются по горизонтали.^73.jpg^Потом завершаем эскиз и выдавливаем окружности на 7 мм.^74 Придадим нужный цвет детали. Для этого выбираем \"Appearance\" во вкладке \"Modify\". Наша деталь готова.^75.jpg^Нам потребуется ещё одна деталь. Создаем эскиз. Для этого в левой части экрана выбираем плоскость XZ, нажимаем левой кнопкой мыши и в появившемся меню выбираем “Create Sketch”.^76.jpg^На появившейся плоскости создаем окружность. Для этого в меню “Sketch” выбираем “Center Diameter Circle”.^77.jpg^В центре плоскости находишь центральную точку и щелкаем на неё.^78.jpg^Отводим мышку немного в сторону и задаем размер “4”. Нажимаем Enter.^79.jpg^В меню “Create” находим “Extrude” и щелкаем на него.^80.jpg^Щелкаем на нашу окружность и вводим размер “”20.5”. Нажимаем Enter.^81.jpg^В итоге мы получили такую деталь. ^82.jpg^Для сборки детали пожалуйста скачайте готовые части и посмотрите видео:"
        },
        {
          "name": "Видео",
          "content": "https://www.youtube.com/embed/engt3ZIgTLo"
        },
        {
          "name": "Готовые части",
          "content": "Для того, чтобы собрать клещи, скачайте ^parts.zip^"
        },
        {
          "name": "Видео по сборке",
          "content": "https://www.youtube.com/embed/PXB4aLrUC-4"
        }
      ]
    },
    {
      "id": 5,
      "parts": [
        {
          "name": "Брус",
          "content": "Перед тем как начать, вам необходимо запустить Fusion 360. Создадим эскиз. Для этого в левом меню выбираем плоскость XY, щелкаем левой кнопкой мыши и наживаем “Create Sketch”.^1.jpg^Нам понадобится создать прямоугольник. Для этого в меню “Sketch” выбираем “2-Point Rectangle”.^2.jpg^Кликаем в случайное место плоскости, отводим немножко мышку в сторону. Получается прямоугольник. Задаем размеры “115.942” в длину и “35” в ширину. Для переключения между размерами нажмите Tab. В итоге должно получиться как на рис. ниже (если он будет стоять вертикально, то не страшно). Нажимаем Enter.^3.jpg^Далее необходимо скруглить края. Для этого в меню “Sketch” выбираем “Fillet”.^4.jpg^Нажимаем на 2 любые смежные грани (либо на угол между ними). Угол закруглится. В поле размера введем “17.5”. Повторим для всех граней.^5   ^6.jpg^Далее нам необходимо создать отверстия. Для этого в меню “Sketch” выбираем “Center Diameter Circle”.^7.jpg^Далее нажимаем на точку, на которую показывает стрелочка.^8.jpg^Отводим мышку немного в сторону и в поле размера вводим “20”. Нажимаем Enter.^9.jpg^Повторяем также, с другой стороны.^10.jpg^В меню “Create” выбираем функцию “Extrude”.^11.jpg^Нажимаем на наш эскиз, чтобы он выделился синим. Не выделяйте окружности, если выделили, то нажмите по ним ещё раз. В поле размера введите “10”. Нажмите Enter.^12.jpg^Далее необходимо покрасить деталь. Для этого необходимо на вкладке “Modify” нажать на “Appearance”.^13.jpg^В появившемся справа окне идите по пути “Plastic –> Translucent”.^14.jpg^Среди цветов в папке “Translucent” выберите красный и мышкой потяните его на деталь.^15.jpg^В итоге мы получили такую деталь.^16.jpg^"        },
        {
          "name": "Цилиндр",
            "content": "Для сборки, нам потребуется ещё одна деталь. Создаем эскиз. Для этого в левой части экрана выбираем плоскость XZ, нажимаем левой кнопкой мыши и в появившемся меню выбираем “Create Sketch”.^17.jpg^На появившейся плоскости создаем окружность. Для этого в меню “Sketch” выбираем “Center Diameter Circle”.^18.jpg^В центре плоскости находишь центральную точку и щелкаем на неё.^19.jpg^Отводим мышку немного в сторону и задаем размер “20”. Нажимаем Enter.^20.jpg^В меню “Create” находим “Extrude” и щелкаем на него.^21.jpg^Щелкаем на нашу окружность и вводим размер ”90”. Нажимаем Enter.^22.jpg^В итоге мы получили такую деталь.^23.jpg^"
        },
        {
          "name": "Ведущее колесо",
          "content": "Для сборки, нам потребуется ещё одна деталь. Создаем эскиз. Для этого в левой части экрана выбираем плоскость XZ, нажимаем левой кнопкой мыши и в появившемся меню выбираем “Create Sketch”. На появившейся плоскости создаем окружность. Для этого в меню “Sketch” выбираем “Center Diameter Circle”.^24.jpg^В центре плоскости находим центральную точку и щелкаем на неё.^25.jpg^Отводим мышку немного в сторону, задаем размер “134.46”. Нажимаем Enter.^26.jpg^В меню “Create” находим “Extrude” и щелкаем на него.^27.jpg^Щелкаем на нашу окружность и вводим размер “10”. Нажимаем Enter.^28.jpg^На верхней поверхности щелкаем левой кнопкой мыши и нажимаем “Create Sketch”.^29.jpg^Создаем в центральной точке окружность с диаметром “61.95”.^30.jpg^Слева от неё создаем ещё две окружности с диаметрами «119.43» и «17.67».^31.jpg^В меню справа нажимаем на Horizontal/Vertical. Далее нажимаем на центры двух последних окружностей. После чего повторяем ту же операцию с любой новой окружностью и окружностью на центральной точке.^32.jpg^В итоге все окружности должны иметь такой значок в центре.^33.jpg^Далее выбираем “Sketch Dimension” во вкладке “Sketch”.^34.jpg^Нажимаем на центры центральной и маленькой окружностей, отводим мышку немного вверх, кликаем и вводим “57.23”. Если ошиблись при вводе, дважды кликните по уже заданному размеру и введите правильное значение. Так же задаем расстояние между центрами центральной и большой окружностей. Вводим “75.118”.^35.jpg^Снова выполняем выдавливание. Для выдавливания выбираем поверхности, показанные на рис. 14. Если выбрали лишние, то кликните по ним ещё раз.^36.jpg^Создаем ещё один эскиз на указанной поверхности.^37.jpg^В центр добавляем окружность с диаметром “20”.^38.jpg^Выдавливаем её на расстояние “-30”, чтобы получилось отверстие.^39.jpg^Далее необходимо покрасить деталь. Для этого используем функцию “Appearance” на вкладке “Modify”.^40.jpg^ Для сборки детали пожалуйста скачайте оставшуюся деталь и посмотрите видео"
        },
        {
          "name": "Видео по сборке и готовые части",
          "content": "https://www.youtube.com/embed/ic6n6fFQAg0 ^parts.zip^"
        }
      ]
    },
    {
      "id": 6,
      "parts": [
        {
          "name": "Патрон",
          "content": "Создайте деталь Патрон. Создадим новый эскиз. Для этого в панели инструментов выберем кнопку Create Sketch.^image001.jpg^В рабочем пространстве появились три плоскости. Щелкните ЛКМ по нижней плоскости (плоскость XY).^image002.jpg^Мы перешли в режим эскиза. Теперь в панели инструментов выберите вкладку Sketch, и в выпадающем меню выберите пункт Circle -> Center Diameter Circle.^image003.jpg^После выбора наведите курсор в начала координат, нажмите ЛКМ и отведите его в сторону. Введите в после размера значение 27мм – диаметр окружности. После этого нажмите ЛКМ ещё два раза.^image004.jpg^^image005.jpg^Выберите в панели инструментов Extrude.^image006.jpg^Наведите курсором на эскиз и нажмите ЛКМ. Появится окно с параметрами выдавливания. Укажите значение выдавливания 20мм. Нажмите кнопку ОК.^image007.jpg^Теперь выберите плоскость XZ и начните в ней эскиз.^image008.jpg^В разделе Create выберите Coil.^image009.jpg^После этого наведите курсором в точку начала координат и нажмите ЛКМ. Укажите диаметр пружины 27мм.^image010.jpg^Появилось меню построения пружины. В меню укажите следующие параметры:Диаметр пружины: 27мм, кол-во витков: 4, высота: 15мм, диаметр витка: 3мм. Операция – Cut. После этого нажмите ОК.^image011.jpg^Создайте эскиз в верхней грани детали. Создайте окружность диаметром 24мм.^image012.jpg^Выберите Extrude для текущего эскиза. Выберите операцию Cut, длину выдавливания 18мм. Нажмите ОК.^image013.jpg^В меню Modify выберите Fillet.^image014.jpg^Выберите спираль и укажите размер сопряжения 0.3мм^image015.jpg^Создайте эскиз в нижней грани детали. Создайте окружность диаметра 20мм.^image016.jpg^Выберите Extrude  и выдавите текущий эскиз на 20мм внутрь детали^image017.jpg^На этой же грани создайте новый эскиз. Создайте окружность диаметра 24мм.^image018.jpg^Выберите Extrude. Требуется выдавить деталь под углом. В меню выдавливания введите следующие параметры:^image019.jpg^Расстояние: 3мм, угол наклона: -45 градусов.Нажмите ОК.^image020.jpg^Создайте ещё один эскиз на новой грани. Создайте окружность диаметром 18 мм.^image021.jpg^Выдавите эскиз со следующими параметрами:Расстояние: 4мм, угол наклона -45 градусов. Нажмите ОК.^image022.jpg^Итоговая деталь:^image023.jpg^Сохраните патрон."
        },
        {
          "name": "Усики",
          "content": "Создаёте новую деталь Усики. Создайте эскиз в плоскости XZ. Создайте следующий эскиз:^image024.jpg^В меню зависимостей (находится справа) выберите пункт Horizontal/Vertical. Поочерёдно щелкните ЛКМ в центр окружности и точку начала координат.^image025.jpg^Выйдите из режима эскиза. Создайте новый эскиз в плоскости XY. В меню Sketch выберите Conic Curve.^image026.jpg^Нажмите ЛКМ на центр окружности из первого эскиза, отведите курсор вверх, снова нажмите ЛКМ. Отведите курсор левее и нажмите ЛКМ. Укажите следующие размеры:Высота линии: 50мм, Высота сгиба: 20мм.^image027.jpg^В разделе Create выберите Sweep.^image028.jpg^В качестве профиля смещения выберите эскиз с окружностью. В качестве пути эскиз с линией. Нажмите ОК.^image029.jpg^В этом же файле создайте ещё один усик. Создаём эскиз в плоскости XZ.^image030.jpg^Создайте ещё один эскиз в плоскости XY. C помощью команды Conic Curve создайте кривую линию.^image031.jpg^С помощью команды Sweep создайте второй усик.^image032.jpg^Создайте новый эскиз в плоскости YZ.  В верхней части учика создайте окружность.^image033.jpg^Спираль создадим с помощью команды Coil.^image034.jpg^^image035.jpg^Сохраните деталь.^image036.jpg^Создайте эскиз в плосоксти XY.Для создания вспомогательной линии кликните два раза ЛКМ по линии и один раз кликните ПКМ. В появившемся списке выберите команду Normal/Construction.^image037.jpg^Чтобы прямоугольники расположились симметрично относительно начала координат, в меню зависимостей выберите Symmetry.^image038.jpg^После этого щелкните по левой и правой стороне прямоугольника, а затем по вспомогательной линии, созданной ранее.^image039.jpg^Удалим ненужные части эскиза. С этой целью в меню Sketch выберите Trim.После этого выберите ЛКМ все линии, находящиеся внутри условной колбы. Результат:^image040.jpg^В разделе Sketch выберите Fillet.^image041.jpg^Нажмите ЛКМ на точку пересечения окружности и прямоугольника.^image042.jpg^Радиус сопряжения: 20мм^image043.jpg^Точно так же скругляем углы в области патрона. Радиус сопряжения: 2мм^image044.jpg^Радиус сопряжения: 1мм^image045.jpg^^image046.jpg^В разделе Sketch выберите Trim и удалите часть эскиза с правой стороны^image047.jpg^В разделе Sketch выберите команду Offset^image048.jpg^Нажмите ЛКМ на эскиз. Длина смещения: 0.6мм^image049.jpg^Замкнём эскиз.^image050.jpg^^image051.jpg^^image052.jpg^И обрежем дно патрона^image053.jpg^^image054.jpg^В разделе Create выберите команду Revolve^image055.jpg^В качестве профиля вращения выберите эскиз, а в качестве оси симметрии – ось симметрии в эскизе.^image056.jpg^Нажмите два раза ЛКМ на деталь, а затем один раз ПКМ. Выберите команду Appearance.^image057.jpg^Откроется меню с выбором материалов.^image058.jpg^Чтобы применить текстуру материала, откройте папку Glass -> Textured. Выберите материал Glass – Frosted Medium и перетащите его ЛКМ на модель.^image059.jpg^^image060.jpg^Сохраните деталь."
        },
        {
          "name": "Сборка",
          "content": "Из папки проекта, зажав ЛКМ, перенесите файл Патрон на рабочее пространство.^image061.jpg^В панели инструментов выберете команду Joint^image062.jpg^При возникновении следующего окна:^image063.jpg^Нажмите Capture Position. Откроется окно зависимостей. Выберите Rigid.^image064.jpg^Наведите курсором на дно патрона и нажмите ЛКМ: ^image065.jpg^Затем нажмите ЛКМ  на дно детали Колба и нажмите ОК.^image066.jpg^Лампочка готова:^image067.jpg^"
        },
        {
          "name": "Видео",
          "content": "https://www.youtube.com/embed/6VNwRU85FZU"
        }
      ]
    },
    {
      "id": 7,
      "parts": [
        {
          "name": "Корпус",
          "content": "Создайте новую деталь. Начните новый эскиз на плоскости YZ. Проведите осевую линию любой длины. Создайте окружность и дугу как показано на рисунке.^image001.jpg^Далее создайте прямоугольник. Верхнюю и нижнюю сторону сделайте вспомогательными.^image002.jpg^Внутри прямоугольника начертите ещё два прямоугольника  ^image003.jpg^Обрежьте все вспомогательные линии (не считая осевой) с помощью команды Trim в разделе Sketch. ^image004.jpg^  ^image005.jpg^Дополните эскиз и укажите размеры как показано ниже.^image006.jpg^Завершите эскиз. С помощью команды Extrude выдавите эскиз на 25.4 мм. ^image007.jpg^Создайте эскиз на передней плоскости детали.^image008.jpg^Начертите линию высотой 39.67 мм поперёк всей детали. С помощью команды Trim обрежьте часть отрезка как показано на рисунке (красным выделена часть, которую требуется обрезать).^image009.jpg^Выйдете из режима эскиза. С помощью команды Extrude выдавите деталь на 127 мм^image010.jpg^ ^image011.jpg^Выберите Modify -> Fillet. Выберите следующие ребра и укажите радиус 3мм и 6мм^image012.jpg^ ^image013.jpg^Начните новый эскиз в плоскости, указанной на рисунке^image014.jpg^Начертите прямоугольник^image015.jpg^Выберите Sketch -> Project/ Include -> Project и выберите отрезки, отмеченные фиолетовым на рисунке^image016.jpg^Завершите эскиз и выдавите эскиз на 31.75 мм^image017.jpg^Создайте эскиз на подсвеченной плоскости^image018.jpg^Начертите дугу со следующими параметрами^image019.jpg^Завершите эскиз и выдавите его насквозь^image020.jpg^Переверните деталь и начните эскиз на днище ^image021.jpg^^image022.jpg^Ножки сделайте с помощью Central Point Arc. Выберите зависимость Coincident и нажмите на точки, указанные на рисунке. Повторите данную операцию с остальными дугами.^image023.jpg^  ^image024.jpg^Так же требуется привязать центры окружностей к центру дуг. Выберите зависимость Horizontal/Vertical и нажмите на точки на рисунке ниже. Повторите операцию с остальными дугами и окружностями^image025.jpg^ ^image026.jpg^Выйдите из режима эскиза и выдавите его со значением -8мм^image027.jpg^С помощью Fillet сделайте сопряжения в указанных частях корпуса.^image028.jpg^ ^image029.jpg^Выберите Create -> Hole.^image030.jpg^Нажмите в любую точку плоскости. ^image031.jpg^Откроется окно параметризации отверстия.^image032.jpg^Нажмите на кнопку Select правее от надписи Reference. Нажмите на указанные места и укажите размер 15.80мм^image033.jpg^Нажмите на вторую кнопку Select, нажмите на указанные места и укажите размер 25.40мм^image034.jpg^В окне параметризации укажите следующие параметры и нажмите ОК.^image035.jpg^Снова выберите Hole, нажмите на ту же плоскость, нажмите на кнопку Select.Выберите следующие точки и укажите размер 53.90мм^image036.jpg^Повторите данную операцию с другими точками и укажите размер 25.40 мм^image037.jpg^В окне параметризации укажите значения, применяемые для первого отверстия. Нажмите ОК.^image038.jpg^Выберите Create -> Threat^image039.jpg^Нажмите на это отверстие и затем кнопку ОК^image040.jpg^Итоговая деталь^image041.jpg^Сохраните деталь под именем Корпус. "
        },
        {
          "name": "Ползунок",
          "content":"Создайте новую деталь. Начните новый эскиз в плоскости XY. Начертите обычную линию из начала координат по оси Y. Нажмите на неё сначала ЛКМ, а затем ПКМ. В появившемся меню выберите Normal/Construction. С помощью Two-point rectangular начертите два прямоугольника, как показано на рисунке. Укажите размеры. Для создания симметрии выберите зависимость Symmetry и выберите сначала правую и левую сторону одного из прямоугольников, а затем линию симметрии. ^image042.jpg^Внутри нижнего прямоугольника начертите ещё один прямоугольник.  ^image043.jpg^С помощью команды Sketch -> Mirror выберите в качестве отражаемой геометрии маленький прямоугольник, а в качестве линии отражении осевую линию. ^image044.jpg^   ^image045.jpg^Выйдете из режима эскиза. Выберите Extrude. Выдавите два больших прямоугольника, не нажимая на маленькие. Выдавите на расстояние 40мм. Нажмите ОК.^image046.jpg^Начните новый эскиз на выделенной плоскости.^image047.jpg^Начертите дугу со следующими параметрами^image048.jpg^Выйдете из режима эскиза и выдавите его насквозь.^image049.jpg^Начните новый эскиз в выделенной плоскости^image050.jpg^Начертите дугу с помощью Sketch -> Arc -> Center Point Arc. Укажите размеры. Выберите зависимость Horizontal/Vertical и выберите центральную точку дуги и её края. ^image051.jpg^ ^image052.jpg^Выйдете из режима эскиза. Выдавите полуокружность с параметром To Object. В качестве объекта выберите ближайшую поверхность.^image053.jpg^Выберите Modify -> Fillet и выделите указанные ребра. Радиус сопряжения: 3 мм^image054.jpg^Начните новый эскиз на выделенной грани.^image055.jpg^Начертите прямоугольную трапецию:^image056.jpg^Выйдите из режима эскиза и выдавите его на -25.4 мм ^image057.jpg^Начните новый эскиз в выделенной плоскости^image058.jpg^Выберите команду Sketch -> Project/Include -> Project.^image059.jpg^Выберите прямоугольники, указанные на рисунке^image060.jpg^Выйдите из режима эскиза и выберите для выдавливания спроецированные прямоугольники. Выдавите прямоугольники по всей длине детали.^image061.jpg^В этой же плоскости начните новый эскиз. Начертите окружность как показано ниже^image062.jpg^Выйдете из режима эскиза. Выберите команду Hole и выберите центром отверстия центр окружности. Укажите следующие параметры отверстия.^image063.jpg^Выберите Thread и нажмите на отверстие. Нажмите ОК.^image064.jpg^ Повторите создание отверстий на грани для зажима со следующими параметрами:^image065.jpg^^image066.jpg^Итоговая деталь^image067.jpg^Сохраните деталь под именем Ползунок. "
        },
        {
          "name": "Вал",
          "content": "Создайте новую деталь.Начните новый эскиз на плоскости XY. Начертите профиль вала (рисунок можно увеличить)^image068.jpg^Выйдете из режима эскиза. Выберите Create -> Revolve.^image069.jpg^В качестве профиля вращения выберите эскиз. В качестве оси вращения выберите отрезок, лежащий на оси X.^image070.jpg^С помощью Threat создайте резьбу на третей ступени вала.^image071.jpg^Выберите Hole и нажмите на первую ступень вала. Получите сквозное отверстие диаметром 7мм^image072.jpg^Сохраните деталь под именем Вал."
        },
        {
          "name": "Ручка",
          "content": "Создайте новую деталь. На плоскости XY создайте эскиз^image073.jpg^Выйдете из режима эскиза и выдавите его на 100мм^image074.jpg^Сохраните деталь под именем Ручка. "
        },
        {
          "name": "Насадка",
          "content": "Создайте новую деталь. Начните эскиз на плоскости XY^image075.jpg^Выдавите эскиз на 10мм^image076.jpg^Выберите Hole создайте два отверстия со следующими параметрами.^image077.jpg^^image078.jpg^Сохраните деталь под именем Насадка."
        },
        {
          "name": "Стержень",
          "content": "Создайте новую деталь. Начните эскиз в плоскости XY и начертите окружность.^image079.jpg^Выдавите деталь на 25мм^image080.jpg^Сохраните деталь под именем Стержень."
        },
        {
          "name": "Сборка",
          "content": "Перейдём к сборке. Создайте новую деталь и сразу же сохраните под именем Сборка. Перенесите из меню на рабочую поверхность все созданные детали. Деталь Стержень перетащите 4 раза, а деталь Насадка – 2 раза.^image081.jpg^Щелкните на Корпус 2 раза ЛКМ, а затем 1 раз ПКМ. В появившемся меню выберите Ground.^image082.jpg^Соединим корпуса. Перейдя в режим сборки Joint,  выберите Slider в списке соединений.^image083.jpg^Нажмите на указанные ниже грани ЛКМ 2 раза.^image084.jpg^^image085.jpg^Выберите в появившемся меню движение по оси X. Нажмите ОК.^image086.jpg^Соединим насадки с корпусом 2. Выберите вид соединения Rigid.^image087.jpg^Выберите следующие рёбра.^image088.jpg^^image089.jpg^Повторите данную операцию с корпусом 1^image090.jpg^^image091.jpg^Закрепим насадки с корпусами стержнями. Выберите вид соединения Rigid и выберете следующие окружности. Повторите операцию с оставшимися стержнями и отверстиями.^image092.jpg^^image093.jpg^Вставим вал в тески. Выберите тип соединения Revolute. ^image094.jpg^Выберите и нажмите на последнюю ступень вала и внутреннюю стенку отверстия корпуса как показано на рисунке.^image095.jpg^^image096.jpg^Вставим ручку в вал. Выберите тип соединения Revolute. Выберите центр ручки и отверстие в валу.^image097.jpg^^image098.jpg^Итоговая сборка^image099.jpg^"
        }
      ]
    },
    {
      "id": 8,
      "parts": [
        {
          "name": "Гайд",
          "content": "Перед тем как начать, вам необходимо запустить Fusion 360. Создадим эскиз. Нажимаем на кнопку в левой части панели инструментов.^1.jpg^Выбираем плоскость, где будем делать эскиз.^2.jpg^Чтобы начертить две линии ,в панели выбираем Sketch -> Line и чертим линии как показано ниже.^3^4.jpg^Укажем для линий размеры. Зайдём в Sketch -> Sketch Dimension, щелкнем по линиям и укажем длину 450mm и расстояние 20mm от центра.^5^6.jpg^Начертим дуги, соединяющие концы линий. Выбираем Sketch -> Arc -> Center Point Arc, выбираем центром дуги точку на одной линии с концами прямых на оси и соединяем концы.^7^8.jpg^Делаем на другом конце детали такую же дугу и расставляем размеры как показано ниже.^9.jpg^Делаем такой же эскиз внутри эскиза, но с другими размерами. Выствляем размеры.^10.jpg^Завершаем эскиз, нажав соответствующую кнопку.^11.jpg^Выдавим деталь. Выбираем в панели инструментов Extrude.^12.jpg^Выбираем эскиз и выдавливаем на 10 мм.^13.jpg^Начинаем новый эскиз и выбираем поверхность детали.^14.jpg^Выберем Sketch -> Offset и выбираем ребра, образовавшиеся в предыдущем эскизе. Смещаем эскиз на 5мм.^15^16.jpg^Воспользуемся проецируемой геометрией. Выбираем Sketch -> Project/Include -> Include 3D Geometry.^17.jpg^Вызываем ребра эскиза. Проецируемая геометрия помечается фиолетовой линией.^18.jpg^Завершаем эскиз и выдавливаем эскиз в две стороны. В одну сторону на 5мм, в другую на 15мм. Не забудьте поменять метод выдавливания Cut на Join.^19.jpg^Итоговая деталь:^20.jpg^Сохраняем, создаём следующую деталь. Создаём вот такой эскиз.^21.jpg^Выдавливаем на 10мм и делаем ещё один эскиз тем же способом, как и в предыдущей детали.^22.jpg^Выдавливаем на 5мм вверх и на 15мм вниз.^23.jpg^Деталь готова:^24.jpg^Создаём новую деталь. Начинаем новый эскиз и выбираем плоскость YZ.^25.jpg^Чертим эскиз:^26.jpg^Требуется совместить нижнюю сторону прямоугольника с осью Х. В окне зависимостей выбираем Coincident. Затем выбираем нижнюю сторону и начало координат.^27^28.jpg^В нижней части эскиза чертим произвольную трапецию. Длина нижнего основания 30 мм.^29.jpg^С помощью указателя размеров так же можно указывать угол между линиями. Выбираем нижнее основание и одну из сторон. Ставим угол 60 градусов. Повторить с противоположной стороной. Дополните эскиз размерами, как указано ниже.^30.jpg^Требуется удалить линию пересечения прямоугольника и трапеции. Заходим в Sketch -> Trim. Trim позволяет обрезать лишние участки эскиза.^31.jpg^Выбираем линию пересечения эскизов.^32.jpg^Итоговый эскиз^33.jpg^Принимаем эскиз и выдавливаем его симметрично на 70мм.^34.jpg^Теперь нам нужно сделать фаску. Выбираем Modify -> Chamfer^35.jpg^Выбираем ребро детали как на картинке и указываем длину фаски 20мм.^36.jpg^Создаем новый эскиз на передней грани детали.^37^38.jpg^Надо сделать, чтобы правая сторона прямоугольника совпала с профилем детали. В окне зависимостей выбираем Collinear.^39.jpg^ДВыбираем правую сторону прямоугольника и правую сторону профиля детали. Выдавим получившийся эскиз на 50мм.^40.jpg^Выбираем Chamfer и два ребра как на картинке. Задаём длину фаски 20мм.^41.jpg^На боковом ребре создаём эскиз и рисуем окружность.^42.jpg^Выдавливаем её насквозь.^43.jpg^Отделим часть, детали, полученную последним выдавливанием. Выбираем Modify -> Split Body.^44.jpg^Выбираем сначала всю деталь, а затем выбираем переднюю часть. По этой плоскости будет происходить разрез.^45.jpg^Теперь без проблем можно отзеркалить деталь. Выбираем Create -> Mirror.^46.jpg^Выбираем переднюю часть детали в качестве объекта для отзеркаливания, а в качестве плоскости симметрии плоскость XY.^47.jpg^Итоговая деталь:^48.jpg^Начнём процесс сборки. Создайте новый дизайн и сохраните его. Перетащите из предоставленных деталей деталь Base. Поверните её с помощью ползунков в центре как показано ниже.^49.jpg^Зафиксируем деталь, чтобы она не мешала движению подвижных частей механизма. Выделяем двойным щелчком ЛКМ и нажимаем ПКМ. В открывшемся меню выбираем Ground.^50.jpg^Далее добавим деталь Crank. Поверните деталь.^51.jpg^Нужно указать взаимосвязи между деталями. Выбираем в панели инструментов Joint.^52.jpg^В появившемся окне выбираем зависимость Cylindrical.^53.jpg^Наводим мышкой на места, указанные ниже, и по очереди нажмем на них.^54.jpg^^55.jpg^Детали соединятся.^56.jpg^Вставьте деталь Operating Lever. Укажите взаимосвязи тем же образом.^57.jpg^^58.jpg^^59.jpg^Вставьте деталь Pin попробуйте вставить её сами. Подсказка:^60.jpg^Теперь добавим в сборку нашу первую сделанную деталь. Расположим её вот так:^61.jpg^Укажем зависимости. В этот раз вкачаете точек зависимости выбираем центры осей.^62.jpg^^63.jpg^Добавляем в сборку деталь Slider и расположите вот так.^64.jpg^Укажем зависимости.^65.jpg^^66.jpg^Укажем ещё одну зависимость для Slider`a. Открываем меню зависимостей и выбираем зависимость Planar. Эта зависимость позволит “скользить” Slider`у по нашей созданной детали.^67.jpg^Указываем следующие зависимости:^68.jpg^^69.jpg^Покрутите рычаг и увидите, что детали взаимодействуют друг с другом..jpg^.jpg^Вставим последнюю сделанную нами деталь.^70.jpg^С помощью Planar указываем зависимости^71.jpg^^72.jpg^И ещё раз^73.jpg^^74.jpg^Таким образом деталь не будет выходить за пределы бортиков при движении. Вставьте Pin и соедините его с деталью самостоятельно.^75.jpg^Вставьте вторую сделанную нами деталь в сборку. Укажите зависимости:^76.jpg^^77.jpg^Соединим два поршня.^78.jpg^^79.jpg^Соединим поршни Pin`ом через Revolute^80.jpg^81.jpg^82.jpg^83.jpg^Вставим Bolt:^84.jpg^85.jpg^86.jpg^Сборка готова. Повращайте ручку и посмотрите, как она будет работать.^87.jpg^"
        }
      ]
    },
    {
      "id": 9,
      "parts": [
        {
          "name": "Гайд",
          "content": ""
        },
        {
          "name": "Сборка",
          "content": ""
        },
        {
          "name": "Сборка",
          "content": ""
        },
        {
          "name": "Видео по сборке",
          "content": "https://www.youtube.com/embed/ic6n6fFQAg0"
        }
      ]
    },
    {
      "id": 0,
      "parts": [
        {
          "name": "Гайд",
          "content": ""
        },
        {
          "name": "Видео по сборке",
          "content": "https://www.youtube.com/embed/ic6n6fFQAg0"
        }
      ]
    }
  ],
  "annotations": [
    {
      "id": 1,
      "annotations": [
        {
          "index": 1,
          "x": 10,
          "y": 10,
          "z": -20,
          "text": "Шестеренка."
        }
      ]
    },
    {
      "id": 2,
      "annotations": [
        {
          "index": 1,
          "x": -75,
          "y": 790,
          "z": 210,
          "text": "Коллектор."
        }
      ]
    }
  ]
}
